### ISSUE TITLE
Main method not found

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/IGUANA#16]
I tested the new version 0.3, but if I run 
`java -cp "./lib/*" de.uni_leipzig.iguana.benchmark.Benchmark config.xml`

I get an "Main method not found in class de.uni_leipzig.iguana.benchmark.Benchmark, please define the main method as: public static void main(String[] args)"

May it needs changed to:
`java -cp "./lib/*" de.uni_leipzig.iguana.benchmark.Main config.xml` ?

**Comment by TortugaAttack** [comment]
yes it needs to change to java -cp "./lib/*" de.uni_leipzig.iguana.benchmark.Main config.xml  
As i tidied up some code, the Main method is now de.uni_leipzig.iguana.benchmark.Main ;)

**Comment by TortugaAttack** [comment]
changed ;)
