### ISSUE TITLE
missing maven dependency

### ISSUE THREAD

**Issue by JJ-Author** [AKSW/IGUANA#36]
Missing artifact org.bio_gene.wookie:connection:jar:0.0.1-SNAPSHOT	pom.xml	/iguana	line 389	Maven Dependency Problem

**Comment by TortugaAttack** [comment]
If you use the develop branch and latest commit: mvn clean should do the trick 
If you use the master branch i will merge the develop branch in the master branch later on ;)

**Comment by JJ-Author** [comment]
the groupid and artifact id in the latest develop commit are still missing for a lot of dependencies 

`Failed to execute goal on project iguana: Could not resolve dependencies for project org.aksw:iguana:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.lexicon:jdbc4sparql:jar:0.0.1, it.unimi.dsi:dsiutils:jar:1.0.10, de.uni_leipzig.aksw:feasible:jar:1.0, it.unimi.dsi:fastutil:jar:5.1.5, prefuse:prefuse:jar:1.0, semiosys:semiosys:jar:1.0, sqljdbc:sqljdbc:jar:1.0, weka:weka:jar:1.0, jung-algorithms:jung-algorithms:jar:2.0.1, jung-api:jung-api:jar:2.0.1, jung-graph-impl:jung-graph-impl:jar:2.0.1, javaml:javaml:jar:0.1.5, jtds:jtds:jar:1.2.2, Jama:Jama:jar:1.0.2, IOWrapper:IOWrapper:jar:1.0, CW:CW:jar:1.0, cooccaccess:cooccaccess:jar:1.0, colt:colt:jar:1.0, ajt:ajt:jar:1.20, AffinityPropagationConsole:AffinityPropagationConsole:jar:1.0, asv-toolbox_util_CommonFileChooser:asv-toolbox_util_CommonFileChooser:jar:1.0, algorithms:EdJoin:jar:Plus, net.sf.javailp:javailp:jar:1.2a, lpsolve:lpsolve:jar:55j, cugar:cugar:jar:0.6.0, LIMES:LIMES:jar:0.6.3.2, de.uni_leipzig.informatik:swp13_sc:jar:0.0.1-SNAPSHOT, annotations:annotations:jar:7.0.3, conja:conja:jar:1.0.6-SNAPSHOT, jlibsvm:jlibsvm:jar:0.91-SNAPSHOT, JSAP:JSAP:jar:2.0a-ds1, jts:jts:jar:1.13, lingpipe:lingpipe:jar:4.1.0, ml:ml:jar:0.911-SNAPSHOT, runutils:runutils:jar:0.91, stats:stats:jar:0.93, symja:symja:jar:2012-04-08, trees:trees:jar:1.023, java:java:jar:json, jmatharray:jmatharray:jar:1.0, simmetrics:simmetrics:jar:1.6.2, SSJoinJava:SSJoinJava:jar:1.0, jgap:jgap:jar:1.0, jgraph:jgraph:jar:1.0, jgraphx:jgraphx:jar:1.0, LBJ2:LBJ2:jar:1.0, LBJ2Library:LBJ2Library:jar:1.0, LbjNerTagger:LbjNerTagger:jar:1.0, libsvm:libsvm:jar:1.0: Could not find artifact org.lexicon:jdbc4sparql:jar:0.0.1 in clapper-org-maven-repo (http://maven.clapper.org/) `

**Comment by TortugaAttack** [comment]
They had system paths as most of them wasn't in a maven repo. 
Those were replaced in the latest commit by a plugin which copies the jar files in the src/main/resources/lib folder into your local maven repo as soon as you execute 
`mvn clean`

But if that doesnt work, we must look what else could be the problem. 
Do you use eclipse or another IDE?

**Comment by JJ-Author** [comment]
i use eclipse Mars.2  , tried it a couple of times with running mvn clean from eclipse  but it was showing me the error posted above again and again, i finally got it working by checking the option "resolve workspace artifacts" within the run configurations dialog for maven builds.. so this was maybe caused by the maven eclipse plugin

**Comment by TortugaAttack** [comment]
Okay. Strange definitley need to check why this happens. 
But nice that it works now.
