### ISSUE TITLE
Configuration reference manual

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/IGUANA#66]
@TortugaAttack hi!

Would be nice to have a doc with description for all the params for the configuration file. For example, in [this tutorial](http://iguana-benchmark.eu/tut_dbpsb.html) it is written that "timelimit" is measured in ms. Warmup time is measured in minuted or? (by default for DBPSB it is set to 20, and it is definitely not ms or seconds).

The perfect solution would be to have something similar to [this](https://docs.docker.com/engine/reference/commandline/service_create/), but for XML configuration parameters.

**Comment by TortugaAttack** [comment]
http://iguana-benchmark.eu/gettingstarted.html
It is sufficient for your needs?

**Comment by TortugaAttack** [comment]
btw: the next version will come with a whole new (and way more detailed) documentation (inspired by docker)
